
name: padosi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  provider: ^6.1.5+1
  go_router: ^13.0.1
  image_picker: ^1.2.0
  google_maps_flutter: ^2.13.1
  geocoding: ^4.0.0
  syncfusion_flutter_charts: ^31.1.23
  video_player: ^2.10.0
  firebase_auth: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Billabong
      fonts:
        - asset: fonts/Billabong.ttf
